<?php

function media_webdam_install() {
  $vocabulary = \Drupal\taxonomy\Entity\Vocabulary::create(array(
      'name' => 'Webdam keywords',
      'vid' => 'webdam_vocab',
      'description' => 'Vocabulary of Webdam keywords',
  ));
  $vocabulary->save();
}


function media_webdam_uninstall() {
  $vocab = \Drupal\taxonomy\Entity\Vocabulary::load('webdam_vocab');
  if ($vocab) {
    $vocab->delete();
  }
}